//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sentinela.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sentinela.Exception.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error!!.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oops! This request requires an access token..
        /// </summary>
        public static string VALIDATION_ACCESS_TOKEN_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_ACCESS_TOKEN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oops! The asset type is invalid..
        /// </summary>
        public static string VALIDATION_ASSET_TYPE_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_ASSET_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The current password provided is incorrect..
        /// </summary>
        public static string VALIDATION_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("VALIDATION_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oops! Email alredy in use..
        /// </summary>
        public static string VALIDATION_EMAIL_ALREDY_EXISTS {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_ALREDY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oops! That email doesn&apos;t look right..
        /// </summary>
        public static string VALIDATION_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oops! Email is required..
        /// </summary>
        public static string VALIDATION_EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oops! Hostname already in use..
        /// </summary>
        public static string VALIDATION_HOSTNAME_ALREDY_EXISTS {
            get {
                return ResourceManager.GetString("VALIDATION_HOSTNAME_ALREDY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oops! The hostname is required..
        /// </summary>
        public static string VALIDATION_HOSTNAME_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_HOSTNAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oops! The Idempotency-Key header is required..
        /// </summary>
        public static string VALIDATION_IDEMPOTENCY_KEY_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_IDEMPOTENCY_KEY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oops! Something is wrong..
        /// </summary>
        public static string VALIDATION_LOGIN_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_LOGIN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oops! The metric is invalid..
        /// </summary>
        public static string VALIDATION_METRIC_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_METRIC_INVALID", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oops! Name is required..
        /// </summary>
        public static string VALIDATION_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oops! The page must be greater than or equal to 1..
        /// </summary>
        public static string VALIDATION_PAGE_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_PAGE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oops! The page size must be between 1 and 100..
        /// </summary>
        public static string VALIDATION_PAGE_SIZE_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_PAGE_SIZE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password must be at least 8 characters long..
        /// </summary>
        public static string VALIDATION_PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oops! Password is required..
        /// </summary>
        public static string VALIDATION_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oops! You don&apos;t have access to this feature..
        /// </summary>
        public static string VALIDATION_RESOURCE_ACCESS_DENIED {
            get {
                return ResourceManager.GetString("VALIDATION_RESOURCE_ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oops! The batch must have at least one sample..
        /// </summary>
        public static string VALIDATION_SAMPLES_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_SAMPLES_REQUIRED", resourceCulture);
            }
        }
    }
}
